# 02 - Dataset Labeling

This notebook analyzes the original labels and metadata of the video datasets
used for the Crowd Violence / Riot Risk Detection project.

Objectives:
- Inspect the original labeling structure
- Analyze class distributions
- Understand video-to-label relationships
- Preserve dataset provenance
- Prepare a unified video-level manifest

Important:
- Original dataset files will not be modified.
- Dataset splits will not be created here.
- No frame extraction or model training will be performed here.

In [3]:
from pathlib import Path
import pandas as pd

In [4]:
PROJECT_ROOT = Path("..")

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"

RWF_DIR = RAW_DATA_DIR / "rwf2000"
VIOLENTFLOWS_DIR = RAW_DATA_DIR / "violentflows"

print("RWF-2000:", RWF_DIR.resolve())
print("Violent-Flows:", VIOLENTFLOWS_DIR.resolve())

RWF-2000: C:\Users\shlok\riot detection\crowd-violence-ml\data\raw\rwf2000
Violent-Flows: C:\Users\shlok\riot detection\crowd-violence-ml\data\raw\violentflows

In [5]:
violence_csv = VIOLENTFLOWS_DIR / "Violence.csv"
nonviolence_csv = VIOLENTFLOWS_DIR / "NonViolence.csv"

violence_df = pd.read_csv(violence_csv)
nonviolence_df = pd.read_csv(nonviolence_csv)

print("Violence CSV shape:", violence_df.shape)
print("NonViolence CSV shape:", nonviolence_df.shape)

Violence CSV shape: (123, 6)
NonViolence CSV shape: (123, 6)

In [6]:
print("Violence columns:")
print(violence_df.columns.tolist())

print("\nNonViolence columns:")
print(nonviolence_df.columns.tolist())

Violence columns:
['search key word', 'simplified video title', 'nickname of the person who uploaded the video', 'video identifier', ' video URL', 'Range']

NonViolence columns:
['search key word', 'simplified video title', 'nickname of the person who uploaded the video', 'video identifier', ' video URL', 'Range']

In [7]:
display(violence_df.head())

,search key word,simplified video title,nickname of the person who uploaded the video,video identifier,video URL,Range
0,balcony football violence,Brannik_Football_Violence,Nattevandring,ysW-tGv-YjI,http://www.youtube.com/watch?v=kW23lUV6oFk,2:17-2:21
1,balcony football violence,British_Football_Hooligans_Mix_3,MorningGlory1997,kW23lUV6oFk,http://www.youtube.com/watch?v=kW23lUV6oFk,2:37-2:41
2,crowd violence,Roma_V_Man_Utd_Police_beating_crowd,Beck84Utd,jwtg8AkcAfc,http://www.youtube.com/watch?v=jwtg8AkcAfc,008-13
3,crowd violence,Man_Utd_vs_Roma_Crowd_Trouble,uncychris,ZGI5vlDMpJA,http://www.youtube.com/watch?v=ZGI5vlDMpJA,004-7
4,fans violence,Accidents_Fights_Violence_Tragedies_Hooligans_...,darkhero00,PgujG07PUq0,http://www.youtube.com/watch?v=PgujG07PUq0,27-31

In [8]:
display(nonviolence_df.head())

,search key word,simplified video title,nickname of the person who uploaded the video,video identifier,video URL,Range
0,football crowds cheering,Andres_Iniesta_Standing_Ovations,allas11,WKv7pmjgDeg,http://www.youtube.com/watch?v=WKv7pmjgDeg,006-9
1,football crowds cheering,Arkansas_vs_ULM_September_11_2010_Woo_Pig_Sooie,jayd243,RfMRWTLGenc,http://www.youtube.com/watch?v=RfMRWTLGenc,0-3
2,football crowds cheering,Australia_vs_Ghana,cubicspacedivision,hy9sgs_Rzbg,http://www.youtube.com/watch?v=hy9sgs_Rzbg,50-53
3,football crowds cheering,Cal_Beats_Stanford_Big_Game_2002_short_low_res...,belmonto,LXfVtmNHkGU,http://www.youtube.com/watch?v=LXfVtmNHkGU,013-16
4,football crowds cheering,Chang_Rai_United_Football_Match,goldfly,_aTVnHfqClA,http://www.youtube.com/watch?v=_aTVnHfqClA,0-3

In [11]:
print("Checking whether CSV video identifiers are embedded in filenames...\n")

violence_matches = 0
nonviolence_matches = 0

for identifier in violence_ids:
    matches = [v for v in vf_videos if identifier in v.stem]
    
    if matches:
        violence_matches += 1

for identifier in nonviolence_ids:
    matches = [v for v in vf_videos if identifier in v.stem]
    
    if matches:
        nonviolence_matches += 1

print("Violence identifiers found inside filenames:", violence_matches)
print("NonViolence identifiers found inside filenames:", nonviolence_matches)

Checking whether CSV video identifiers are embedded in filenames...

Violence identifiers found inside filenames: 46
NonViolence identifiers found inside filenames: 68

In [13]:
print("Example identifier → filename matches:\n")

for identifier in list(violence_ids)[:10]:
    matches = [v for v in vf_videos if identifier in v.stem]
    
    print(f"Identifier: {identifier}")
    
    for match in matches:
        print(f"  → {match.name}")
    
    print()

Example identifier → filename matches:

Identifier: U-CsDQik3sw

Identifier: ZGI5vlDMpJA
  → crowd_violence__Man_Utd_vs_Roma_Crowd_Trouble__uncychris__ZGI5vlDMpJA.avi

Identifier: EaCpQJLdxJ8
  → fans_violence__FootBall_Fans_Violence__xxxXLsDXxxx__EaCpQJLdxJ8.avi
  → football_fans__FootBall_Fans_Violence__xxxXLsDXxxx__EaCpQJLdxJ8.avi

Identifier: MgXe0isUnSg

Identifier: Q2k-ZHCZBAk
  → Hooligans_violence__Fuck_police_Let_s_riot__tigerland2222__Q2k-ZHCZBAk.avi

Identifier: pn6CNLi3UhA
  → balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA.avi

Identifier: kW23lUV6oFk

Identifier: 9tkj8gtIoNM

Identifier: g6p_k37oWws
  → balcony_football_violence__Football_Hooligans_Bury_v_Stockport_1998__MorningGlory1997__g6p_k37oWws.avi

Identifier: jzmiAbjN6Mw
  → fans_violence__Hardcore_Supporter_Fight_Extreme_Violence_Final_Four_Volley_Praha__javierulf__jzmiAbjN6Mw.avi

In [14]:
print("Violence identifiers with NO filename match:\n")

no_matches = []

for identifier in violence_ids:
    matches = [v for v in vf_videos if identifier in v.stem]
    
    if not matches:
        no_matches.append(identifier)

for identifier in no_matches[:20]:
    print(identifier)

print("\nTotal without matches:", len(no_matches))

Violence identifiers with NO filename match:

U-CsDQik3sw
MgXe0isUnSg
kW23lUV6oFk
9tkj8gtIoNM
9a616Ppoeak
MFDeI2bK2Pk
JfLHSqKm9zg
WSCF2iLuRyk
bXb1IT7gY8
wutK9msi4yo
6xAQGS0fodE
anRuF6MBO-s
GnfpwW6sMkc
ydTykaGO-Dg
3mXS25xDG6I
1XbY1Sr2Obw
f66MTrNLPL0
t9IYNex9Nn4
--3xfJHXlOc
GcP3SiwkmGo

Total without matches: 65

In [15]:
from collections import Counter

vf_label_counts = Counter()

for video in vf_videos:
    parts = video.parts

    if "Violence" in parts:
        vf_label_counts["violence"] += 1
    elif "NonViolence" in parts:
        vf_label_counts["nonviolence"] += 1
    else:
        vf_label_counts["unknown"] += 1

print("Violent-Flows labels from directory structure:")
for label, count in vf_label_counts.items():
    print(f"{label}: {count}")

Violent-Flows labels from directory structure:
nonviolence: 123
violence: 123

In [16]:
print("Checking for videos with unknown labels...\n")

unknown_videos = [
    video for video in vf_videos
    if "Violence" not in video.parts and "NonViolence" not in video.parts
]

print("Unknown videos:", len(unknown_videos))

for video in unknown_videos:
    print(video)

Checking for videos with unknown labels...

Unknown videos: 0

In [17]:
rwf_records = []

for video in RWF_DIR.rglob("*"):
    if not video.is_file() or video.suffix.lower() != ".avi":
        continue

    parts = video.parts

    if "Train_Fight" in parts:
        label = "violence"
        split = "train"
    elif "Train_NonFight" in parts:
        label = "nonviolence"
        split = "train"
    elif "Val_Fight" in parts:
        label = "violence"
        split = "val"
    elif "Val_NonFight" in parts:
        label = "nonviolence"
        split = "val"
    else:
        continue

    rwf_records.append({
        "video_path": str(video),
        "source_dataset": "RWF-2000",
        "source_video_id": video.stem,
        "original_split": split,
        "label": label
    })

print("RWF-2000 records:", len(rwf_records))

RWF-2000 records: 2000

In [18]:
vf_records = []

for video in vf_videos:
    parts = video.parts

    if "Violence" in parts:
        label = "violence"
    elif "NonViolence" in parts:
        label = "nonviolence"
    else:
        continue

    # The numbered folder (1–5) preserves the original dataset grouping.
    group = next(
        (part for part in parts if part in {"1", "2", "3", "4", "5"}),
        None
    )

    vf_records.append({
        "video_path": str(video),
        "source_dataset": "Violent-Flows",
        "source_video_id": video.stem,
        "original_split": group,
        "label": label
    })

print("Violent-Flows records:", len(vf_records))

Violent-Flows records: 246

In [19]:
all_records = rwf_records + vf_records

raw_manifest = pd.DataFrame(all_records)

print("Total records:", len(raw_manifest))
print("\nClass distribution:")
print(raw_manifest["label"].value_counts())

print("\nDataset distribution:")
print(raw_manifest["source_dataset"].value_counts())

display(raw_manifest.head())

Total records: 2246

Class distribution:
label
violence       1123
nonviolence    1123
Name: count, dtype: int64

Dataset distribution:
source_dataset
RWF-2000         2000
Violent-Flows     246
Name: count, dtype: int64

,video_path,source_dataset,source_video_id,original_split,label
0,..\data\raw\rwf2000\train\Train_Fight\-1l5631l...,RWF-2000,-1l5631l3fg_0,train,violence
1,..\data\raw\rwf2000\train\Train_Fight\-1l5631l...,RWF-2000,-1l5631l3fg_1,train,violence
2,..\data\raw\rwf2000\train\Train_Fight\-1l5631l...,RWF-2000,-1l5631l3fg_2,train,violence
3,..\data\raw\rwf2000\train\Train_Fight\0H2s9UJc...,RWF-2000,0H2s9UJcNJ0_0,train,violence
4,..\data\raw\rwf2000\train\Train_Fight\0H2s9UJc...,RWF-2000,0H2s9UJcNJ0_2,train,violence

In [20]:
print("Missing values:")
print(raw_manifest.isnull().sum())

print("\nDuplicate rows:", raw_manifest.duplicated().sum())

print(
    "Duplicate video paths:",
    raw_manifest["video_path"].duplicated().sum()
)

Missing values:
video_path         0
source_dataset     0
source_video_id    0
original_split     0
label              0
dtype: int64

Duplicate rows: 0
Duplicate video paths: 0

In [21]:
print("\nRecords by dataset and label:")
print(
    raw_manifest
    .groupby(["source_dataset", "label"])
    .size()
)

Records by dataset and label:
source_dataset  label
RWF-2000        nonviolence    1000
                violence       1000
Violent-Flows   nonviolence     123
                violence        123
dtype: int64

In [22]:
from pathlib import Path

MANIFEST_DIR = PROJECT_ROOT / "data" / "manifests"
MANIFEST_DIR.mkdir(parents=True, exist_ok=True)

raw_manifest_path = MANIFEST_DIR / "raw_manifest.csv"

raw_manifest.to_csv(raw_manifest_path, index=False)

print("Saved:", raw_manifest_path.resolve())
print("Rows:", len(raw_manifest))

Saved: C:\Users\shlok\riot detection\crowd-violence-ml\data\manifests\raw_manifest.csv
Rows: 2246

In [23]:
check_manifest = pd.read_csv(raw_manifest_path)

print("Reloaded rows:", len(check_manifest))
print("\nColumns:")
print(check_manifest.columns.tolist())

Reloaded rows: 2246

Columns:
['video_path', 'source_dataset', 'source_video_id', 'original_split', 'label']

In [24]:
print(check_manifest["label"].value_counts())
print()
print(check_manifest["source_dataset"].value_counts())

label
violence       1123
nonviolence    1123
Name: count, dtype: int64

source_dataset
RWF-2000         2000
Violent-Flows     246
Name: count, dtype: int64